config/routes.rb
Rails.application.routes.draw do
    get 'contact/index' => 'contact#index', as: :contact
    post 'contact/create' => 'contact#create', as: :new_contact

    get 'destinations/all' => 'destinations#all', as: :destinations_all
    get 'destinations/:id/admin' => 'destinations#show_admin', as: :destination_admin

    get 'islands/all' => 'islands#all', as: :islands_all
    get 'islands/:id/admin' => 'islands#show_admin', as: :island_admin

    get 'hotels/all' => 'hotels#all', as: :hotels_all
    get 'hotels/:id/admin' => 'hotels#show_admin', as: :hotel_admin

    get 'promos/all' => 'promos#all', as: :promos_all
    get 'promos/:id/admin' => 'promos#show_admin', as: :promo_admin

    resources :destinations
    resources :islands
    resources :hotels
    resources :referral_links
    resources :promos
    resources :contact

    root 'home#index'

    if Rails.env.production?
        devise_for :admins, :controllers => { :registrations => "registrations" }
    else
        devise_for :admins
    end

end

app/models/island.rb
class Island < ActiveRecord::Base
    belongs_to :destination
    has_many :hotels, dependent: :destroy

    accepts_nested_attributes_for :hotels,
                                  :allow_destroy => true,
                                  :reject_if => lambda { |a| a[:name].blank? && a[:description].blank? }
end

app/controllers/islands_controller.rb
class IslandsController < ApplicationController
    before_action :authenticate_admin!, only: [:new, :create, :update, :edit, :destroy, :index, :show_admin]

    def new
        @island = Island.new
        @destinations = Destination.all
        2.times do
            @island.hotels.build
        end
        render :layout => 'application_nobanner'
    end

    def create
        @island = Island.new(island_params)
        @params = params
        if @island.save
            redirect_to island_admin_path @island, notice: 'Island was created successfully'
        end
    end

    def update
        island = Island.find(params[:id])

        if island.update!(island_params)
            redirect_to island_admin_path island, notice: 'Island was updated successfully'
    end end

    def edit
        @island = Island.find(params[:id])
        
        @destinations = Destination.all
        render :layout => 'application_nobanner'
    end

    def destroy
        island = Island.find(params[:id])

        if island.destroy
            redirect_to island_admin_path, notice: 'Island was deleted successfully'
        end
    end

    def index
        @islands = Island.all
    end

    def all
        @islands = Island.all
        render :layout => 'application_nobanner'
    end

    def show
        @island = Island.find(params[:id])
        @hotels = @island.hotels
    end

    def show_admin
        @island = Island.find(params[:id])
        render :layout => 'application_nobanner'
    end

    private
        def island_params
            params.require(:island).permit(:name, :description, :destination_id, :hotels_attributes => [:id, :name, :description, :_destroy])
        end
        def hotel_params
            params.require(:hotels).permit(:name, :description)
        end
end

app/helpers/islands_helper.rb
module IslandsHelper
end

app/views/islands/_form.html.erb
<%= nested_form_for @island, :html => {:class => "well", :role => "form" } do |f| %>
<div class="row">
  <div class="form-group col-sm-6">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :maxlength => '255', :size=>'25',:class => 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group col-sm-6">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :maxlength => '2000', :size=>'150', :class => 'text_area form-control' %>
    </div>
  </div>
</div>
<div class="row">
  <div class="form-group col-sm-6">
    <%= f.label :destination_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.select(
        :destination_id, 
        options_from_collection_for_select(@destinations, 'id', 'name', @island.destination_id),
        {},
        html_options = {:class => 'form-control'}) %>
    </div>
  </div>
</div>

  <h3>Hotels:</h3>
  <%= f.fields_for :hotels %>
  <p><%= f.link_to_add "Add a hotel", :hotels %></p>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                islands_all_path, :class => 'btn' %>
  </div>
<% end %>

app/views/islands/_hotel_fields.html.erb
<div class="row">
	<div class="form-group col-sm-6">
	  <%= f.label :name, :class => 'control-label' %>
	  <div class="controls">
	    <%= f.text_field :name, :maxlength => '255', :size=>'25', :class => 'text_field form-control' %>
	  </div>
	</div>
	<div class="form-group col-sm-6">
	  <%= f.label :description, :class => 'control-label' %>
	  <div class="controls">
	    <%= f.text_area :description, :maxlength => '2000', :size=>'150', :class => 'text_area form-control' %>
	  </div>

	  <p><%= f.link_to_remove "Remove this hotel", :class => "pull-right" %></p>
	</div>
</div>

app/views/islands/all.html.erb
<%- model_class = Island -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:id) %></th>
    <th><%= model_class.human_attribute_name(:name) %></th>
    <th><%= model_class.human_attribute_name(:description) %></th>
    <th><%= model_class.human_attribute_name(:destination_id) %></th>
    <th><%= model_class.human_attribute_name(:created_at) %></th>
    <th><%=t '.actions', :default => t("helpers.actions") %></th>
  </tr>
  </thead>
  <tbody>
  <% @islands.each do |island| %>
      <tr>
        <td><%= link_to island.id, island_admin_path(island) %></td>
        <td><%= island.name %></td>
        <td><%= island.description %></td>
        <td><%= link_to island.destination.name, controller: 'destinations', action: 'show', id: island.destination_id %></td>
        <td><%= island.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_island_path(island), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      island_path(island),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_island_path,
            :class => 'btn btn-primary' %>

app/views/islands/create.html.erb
<h1>Islands#create</h1>
<p>Find me in app/views/islands/create.html.erb</p>
<div><%= debug params %></div>

app/views/islands/destroy.html.erb
<h1>Islands#destroy</h1>
<p>Find me in app/views/islands/destroy.html.erb</p>

app/views/islands/edit.html.erb
<%- model_class = Destination -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/islands/index.html.erb
<div class="row">
  <% @islands.each do |island| %>
      <div class="col-sm-4">
        <h3><%= island.name %></h3>

        <% island.hotels.each do |hotel| %>
            <%= link_to hotel.name, hotel_path(hotel) %>
        <% end %>
      </div>
  <% end %>
</div>

app/views/islands/new.html.erb
<%- model_class = Island -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/islands/show.html.erb
<div class="jumbotron destination_jumbo">
  <div class="container">
    <h1 class="tagline"><%= @island.name %></h1>
  </div>
</div>

<div class="container">
    <div class="tile_row">
      <% @hotels.each do |hotel| %>

          <%= tag "div", :class=>"tile" %>

            <div class="tile_image">

              <%= image_tag("stock.jpg") %>
            </div>

            <div class="well tile_caption">
              <span class="title"><%= hotel.name %></span>
              <% if !hotel.description.blank? %>
                <p><%= hotel.description %></p>
              <% end %>
            </div>

          </div>
      <% end %>
    </div>
</div>

app/views/islands/show_admin.html.erb
<%- model_class = Island -%>
<div class="page-header">
  <h1><%= t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @island.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @island.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:destination_id) %>:</strong></dt>
  <dd><%= @island.destination.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:hotels) %>:</strong></dt>
  <dd>
    <%= if @island.hotels.count == 0; 'None' end %>
    <% @island.hotels.each do |hotel| %>
        <%= link_to hotel.name, hotel_admin_path(hotel) %>
    <% end %>
  </dd>

</dl>
<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              islands_all_path, :class => 'btn' %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_island_path(@island), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              island_path(@island),
              :method => 'delete',
              :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))},
              :class => 'btn btn-danger' %>
</div>

app/views/islands/update.html.erb
<h1>Islands#update</h1>
<p>Find me in app/views/islands/update.html.erb</p>