config/routes.rb
Rails.application.routes.draw do
    get 'contact/index' => 'contact#index', as: :contact
    post 'contact/create' => 'contact#create', as: :new_contact

    get 'destinations/all' => 'destinations#all', as: :destinations_all
    get 'destinations/:id/admin' => 'destinations#show_admin', as: :destination_admin

    get 'islands/all' => 'islands#all', as: :islands_all
    get 'islands/:id/admin' => 'islands#show_admin', as: :island_admin

    get 'hotels/all' => 'hotels#all', as: :hotels_all
    get 'hotels/:id/admin' => 'hotels#show_admin', as: :hotel_admin

    get 'promos/all' => 'promos#all', as: :promos_all
    get 'promos/:id/admin' => 'promos#show_admin', as: :promo_admin

    resources :destinations
    resources :islands
    resources :hotels
    resources :referral_links
    resources :promos
    resources :contact

    root 'home#index'

    if Rails.env.production?
        devise_for :admins, :controllers => { :registrations => "registrations" }
    else
        devise_for :admins
    end

end

app/models/contact.rb
class Contact
 include ActiveModel::Serialization
 extend ActiveModel::Naming
 include ActiveModel::Conversion
 
 attr_accessor :name, :phone, :email, :occasion, :locations
 
 def initialize(attributes = {})
  @name=attributes[:name]
  @phone=attributes[:phone]
  @email=attributes[:email]
  @occasion=attributes[:occasion]
  @locations=attributes[:locations]
 end
  
# persisted is important not to get "undefined method `to_key' for" error
 def persisted?
  false
 end
  
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
    @destinations = Destination.all
    @contact = Contact.new
    render :layout => 'application_nobanner'
  end

  # POST /users
  # POST /users.json
  def create

		locations = params[:contact][:locations] ? params[:contact][:locations].join(", "): ""
		new_contact = contact_params
		new_contact[:locations] = locations
		@contact = Contact.new(new_contact)		
		

    ContactMailer.contact_email(@contact).deliver
    redirect_to contact_path, notice: 'Sent successfully'
  end

  private
    def contact_params
        params.require(:contact).permit(:name, :phone, :email, :occasion, :locations)
    end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/views/contact/ORIGINAL_form.html.erb
<form role="form">
    <div class="form-group">
      <label for="name">Name</label>
      <input type="text" class="form-control" id="name" placeholder="Name">
    </div>
    <div class="form-group">
      <label for="phone">Phone</label>
      <input type="tel" class="form-control" id="phone" placeholder="Phone">
    </div>
    <div class="form-group">
      <label for="exampleInputEmail1">Email address</label>
      <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
    </div>
      <div class="form-group">
        <label for="occasion">Occasion for travel</label>
        <input type="text" class="form-control" id="occasion" placeholder="Occasion">
      </div>
  <div class="form-group">
    <label for="locations">Locations of interest</label>
    <% @destinations.each do |d| %>
        <div class="checkbox">
          <label>
            <input type="checkbox" value="<%= d.name %>">
            <%= d.name %>
          </label>
        </div>
    <% end %>
    <div class="checkbox">
      <label>
        <input type="checkbox" value="other">
        Other
      </label>
    </div>
  </div>
    <button type="submit" class="btn btn-default">Submit</button>
</form>

app/views/contact/_form.html.erb
<%= form_for @contact, url: new_contact_path, method: "post", :html => {id: "contact_form"} do |f| %>
  
  <div class="form-group">
      <%= label_tag "name" %>
      <%= f.text_field :name, placeholder: "Name", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= label_tag "phone" %>
      <%= f.phone_field :phone, placeholder: "Phone", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= label_tag "name", "Email address" %>
      <%= f.email_field :email, placeholder: "Email", class: "form-control" %>
    </div>
      <div class="form-group">
      <%= label_tag "occasion", "Occasion for travel" %>
      <%= f.text_field :occasion, placeholder: "Occasion", class: "form-control" %>
      </div>
  <div class="form-group">
      <%= label_tag "locations", "Locations of interest" %>
     <% @destinations.each do |d| %>
     <div class="checkbox">
        <%= check_box_tag "contact[locations][]", d.name, false, id: "contact_locations_"+d.name %>
        <%= label_tag "contact_locations_"+d.name, d.name %>
    </div>
      <% end %>
    <div class="checkbox">
        <input id="contact_locations_other" name="contact[locations][]" type="checkbox" value="Other">
        <label for="contact_locations_other">Other</label>
    </div>
  </div>
    <%= f.submit "Submit", class: "btn btn-default" %>


<% end %>

app/views/contact/create.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1>Contact Request</h1>
    <p><%= @contact.name %> has requested more information.</p>
    <p>Phone: <%= @contact.phone %></p>
    <p>Email: <%= @contact.email %></p>
    <p>Occasion for travel: 
      <% if !@contact.occasion.blank? %>
        <%= @contact.occasion %>
      <% else %>
        N/A
      <% end %>
    </p>
    
    <p>Locations of interest:
      <% if !@contact.locations.blank? %>
        <%= @contact.locations %>
      <% else %>
        N/A
      <% end %>
    </p>
  </body>
</html>

app/views/contact/index.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-1">
    <h2>Send a request</h2>
    <div class="well">
      <%= render('contact/form') %>
    </div>
  </div>
  <div class="col-md-4 col-md-offset-1">
    <h2>Chat with us</h2>
    <div class="well">
      <p><b>Call or email</b></p>
      <p>816.525.9859</p>
      <p><%= mail_to "trvlsrc@sbcglobal.net" %></p>

      <p><b>Visit today</b></p>
      <div>
        <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d1552.2359239577695!2d-94.37397907825155!3d38.913191430314846!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x87c11f8db3a76e4f%3A0x9c1fb318b9bef043!2sTravel+Source!5e0!3m2!1sen!2sus!4v1406325026778" height="400" frameborder="0" style="border:0"></iframe>
      </div>
    </div>
  </div>
</div>