config/routes.rb
Rails.application.routes.draw do
    get 'contact/index' => 'contact#index', as: :contact
    post 'contact/create' => 'contact#create', as: :new_contact

    get 'destinations/all' => 'destinations#all', as: :destinations_all
    get 'destinations/:id/admin' => 'destinations#show_admin', as: :destination_admin

    get 'islands/all' => 'islands#all', as: :islands_all
    get 'islands/:id/admin' => 'islands#show_admin', as: :island_admin

    get 'hotels/all' => 'hotels#all', as: :hotels_all
    get 'hotels/:id/admin' => 'hotels#show_admin', as: :hotel_admin

    get 'promos/all' => 'promos#all', as: :promos_all
    get 'promos/:id/admin' => 'promos#show_admin', as: :promo_admin

    resources :destinations
    resources :islands
    resources :hotels
    resources :referral_links
    resources :promos
    resources :contact

    root 'home#index'

    if Rails.env.production?
        devise_for :admins, :controllers => { :registrations => "registrations" }
    else
        devise_for :admins
    end

end

app/models/destination.rb
class Destination < ActiveRecord::Base
	has_many :islands, dependent: :destroy
  has_many :hotels, dependent: :destroy

	accepts_nested_attributes_for :islands,
                                :allow_destroy => true,
                                :reject_if => lambda { |a| a[:name].blank? && a[:description].blank? }

  accepts_nested_attributes_for :hotels,
                                :allow_destroy => true,
                                :reject_if => lambda { |a| a[:name].blank? && a[:description].blank? }
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
    before_action :authenticate_admin!, only: [:new, :create, :update, :edit, :destroy, :all, :show_admin]

    def new
        @destination = Destination.new
        1.times do
            @destination.islands.build
            @destination.hotels.build
        end
        render :layout => 'application_nobanner'
    end

    def create
        @destination = Destination.new(destination_params)

        if @destination.save
            redirect_to destination_admin_path @destination, notice: 'Destination was created successfully'
        end
    end

    def update
        destination = Destination.find(params[:id])

        if destination.update!(destination_params)
            redirect_to destination_admin_path destination, notice: 'Destination was updated successfully'
        end
    end

    def edit
        @destination = Destination.find(params[:id])
        render :layout => 'application_nobanner'
    end

    def destroy
        destination = Destination.find(params[:id])

        if destination.destroy
            redirect_to destinations_all_path, notice: 'Destination was deleted successfully'
        end
    end

    def index
        @destinations = Destination.all
    end

    def all
        @destinations = Destination.all
        render :layout => 'application_nobanner'
    end

    def show_admin
        @destination = Destination.find(params[:id])
        render :layout => 'application_nobanner'
    end

    def show
        @destination = Destination.find(params[:id])
        @islands = @destination.islands
        @hotels = @destination.hotels
    end

    private
        def destination_params
            params.require(:destination).permit(
                :name,
                :path,
                :islands_attributes => [:id, :name, :description, :_destroy],
                :hotels_attributes => [:id, :name, :description, :_destroy]
            )
        end
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/views/destinations/_form.html.erb
<%= nested_form_for @destination, :html => {:class => 'well', :role => 'form'} do |f| %>
  <div class="row">
    <div class="form-group col-sm-6">
      <%= f.label :name, :class => '' %>
      <div class="">
        <%= f.text_field :name, :maxlength => '255', :size=>'25', :class => 'text_field form-control' %>
      </div>
    </div>

    <div class="form-group col-sm-6">
      <%= f.label :path, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :path, :maxlength => '255', :size=>'25', :class => 'text_field form-control' %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="form-group">
      <h2>Islands:</h2>
      <%= f.fields_for :islands %>
      <p><%= f.link_to_add "Add an island", :islands %></p>
    </div>
  </div>
  <div class="row">
    <div class="form-group">
      <h2>Hotels:</h2>
      <%= f.fields_for :hotels %>
      <p><%= f.link_to_add 'Add a hotel', :hotels %></p>
    </div>
  </div>
    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  destinations_all_path, :class => 'btn' %>
    </div>
<% end %>

app/views/destinations/_hotel_fields.html.erb
<div class="form-group col-sm-6">
  <%= f.label :name, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :name, :maxlength => '25', :class => 'text_field form-control' %>
  </div>
</div>
<div class="form-group col-sm-6">
  <%= f.label :description, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_area :description, :maxlength => '25', :class => 'text_area form-control' %>
    <p class="pull-right"><%= f.link_to_remove "Remove this hotel" %></p>
  </div>
</div>

app/views/destinations/_island_fields.html.erb
<div class="form-group col-sm-6">
  <%= f.label :name, :class=>'control-label' %>
  <div class="controls">
    <%= f.text_field :name, :maxlength => '25', :class=>'text_field form-control' %>
  </div>
</div>
<div class="form-group  col-sm-6">
  <%= f.label :description, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_area :description, :maxlength => '25', :class => 'text_area form-control' %>
    <p class="pull-right"><%= f.link_to_remove "Remove this island" %></p>
  </div>
</div>

app/views/destinations/all.html.erb
<%- model_class = Destination -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:path) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @destinations.each do |destination| %>
      <tr>
        <td><%= link_to destination.id, destination_admin_path(destination) %></td>
        <td><%= destination.name %></td>
        <td><%= destination.path %></td>
        <td><%=l destination.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_destination_path(destination), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      destination_path(destination),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_destination_path,
            :class => 'btn btn-primary' %>

app/views/destinations/create.html.erb
<h1>Destinations#create</h1>
<p>Find me in app/views/destinations/create.html.erb</p>

app/views/destinations/destroy.html.erb
<h1>Destinations#destroy</h1>
<p>Find me in app/views/destinations/destroy.html.erb</p>

app/views/destinations/index.html.erb
<div class="jumbotron destination_jumbo">
  <div class="container">
    <h1 class="tagline">Destinations</h1>
  </div>
</div>

<div class="container">
    <div class="tile_row">
      <% @destinations.each do |destination| %>

          <div class="tile">

            <div class="tile_image">
              <!--TODO: use the actual path for destination image here.  It just ain't created yet.-->
              <% if destination.path.blank? %>
                <%= image_tag("/stock.jpg") %>
              <% else %>
                <%= image_tag("destinations/#{destination.path}.jpg") %>
              <% end %>
            </div>

            <div class="well tile_caption">
              <span><%= destination.name %></span>
              <%= link_to(content_tag("button", "Read More", :class=>"btn btn-success btn-xs pull-right"), destination_path(destination)) %>
            </div>

          </div>


      <% end %>
    </div>
</div>

app/views/destinations/new.html.erb
<%- model_class = Destination -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/destinations/show.html.erb
<div class="jumbotron destination_jumbo">
  <div class="container">
    <h1 class="tagline"><%= @destination.name %></h1>
  </div>
</div>
<div class="container">
    <div class="tile_row">
      <% @islands.each do |island| %>

          <%= tag "div", :class=>"tile" %>

            <div class="tile_image">

              <%= image_tag("stock.jpg") %>
            </div>

            <div class="well tile_caption">
              <span><%= island.name %></span>
              <%= link_to content_tag("button", "Read More", :class=>"btn btn-success btn-xs pull-right"), island_path(island) %>
            </div>

          </div>
      <% end %>
      <% @hotels.each do |hotel| %>

          <%= tag "div", :class=>"tile" %>

            <div class="tile_image">

              <%= image_tag("stock.jpg") %>
            </div>

            <div class="well tile_caption">
              <span class="title"><%= hotel.name %></span>
              <% if !hotel.description.blank? %>
                <p><%= hotel.description %></p>
              <% end %>
            </div>

          </div>
      <% end %>
    </div>
</div>

app/views/destinations/show_admin.html.erb
<%- model_class = Destination -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @destination.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:path) %>:</strong></dt>
  <dd><%= @destination.path %></dd>
  <dt><strong><%= model_class.human_attribute_name(:islands) %>:</strong></dt>
  <dt><strong><%= model_class.human_attribute_name(:hotels) %>:</strong></dt>
  <dd>
    <%= if @destination.islands.count == 0; 'None' end %>
    <% @destination.islands.each do |island| %>
        <%= link_to island.name, island_admin_path(island) %>
    <% end %>
  </dd>
  <dd>
    <%= if @destination.hotels.count == 0; 'None' end %>
    <% @destination.hotels.each do |hotel| %>
        <%= link_to hotel.name, hotel_admin_path(hotel) %>
    <% end %>
  </dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              destinations_all_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_destination_path(@destination), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              destination_path(@destination),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/destinations/update.html.erb
<h1>Destinations#update</h1>
<p>Find me in app/views/destinations/update.html.erb</p>