config/routes.rb
Rails.application.routes.draw do
    get 'contact/index' => 'contact#index', as: :contact
    post 'contact/create' => 'contact#create', as: :new_contact

    get 'destinations/all' => 'destinations#all', as: :destinations_all
    get 'destinations/:id/admin' => 'destinations#show_admin', as: :destination_admin

    get 'islands/all' => 'islands#all', as: :islands_all
    get 'islands/:id/admin' => 'islands#show_admin', as: :island_admin

    get 'hotels/all' => 'hotels#all', as: :hotels_all
    get 'hotels/:id/admin' => 'hotels#show_admin', as: :hotel_admin

    get 'promos/all' => 'promos#all', as: :promos_all
    get 'promos/:id/admin' => 'promos#show_admin', as: :promo_admin

    resources :destinations
    resources :islands
    resources :hotels
    resources :referral_links
    resources :promos
    resources :contact

    root 'home#index'

    if Rails.env.production?
        devise_for :admins, :controllers => { :registrations => "registrations" }
    else
        devise_for :admins
    end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/contact.rb
class Contact
 include ActiveModel::Serialization
 extend ActiveModel::Naming
 include ActiveModel::Conversion
 
 attr_accessor :name, :phone, :email, :occasion, :locations
 
 def initialize(attributes = {})
  @name=attributes[:name]
  @phone=attributes[:phone]
  @email=attributes[:email]
  @occasion=attributes[:occasion]
  @locations=attributes[:locations]
 end
  
# persisted is important not to get "undefined method `to_key' for" error
 def persisted?
  false
 end
  
end

app/models/customer_review.rb
class CustomerReview < ActiveRecord::Base
end

app/models/destination.rb
class Destination < ActiveRecord::Base
	has_many :islands, dependent: :destroy
  has_many :hotels, dependent: :destroy

	accepts_nested_attributes_for :islands,
                                :allow_destroy => true,
                                :reject_if => lambda { |a| a[:name].blank? && a[:description].blank? }

  accepts_nested_attributes_for :hotels,
                                :allow_destroy => true,
                                :reject_if => lambda { |a| a[:name].blank? && a[:description].blank? }
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
	belongs_to :island
  belongs_to :destination

	has_many :hotel_pictures, dependent: :destroy
end

app/models/hotel_picture.rb
class HotelPicture < ActiveRecord::Base
	belongs_to :hotel
end

app/models/island.rb
class Island < ActiveRecord::Base
    belongs_to :destination
    has_many :hotels, dependent: :destroy

    accepts_nested_attributes_for :hotels,
                                  :allow_destroy => true,
                                  :reject_if => lambda { |a| a[:name].blank? && a[:description].blank? }
end

app/models/promo.rb
class Promo < ActiveRecord::Base
end

app/models/referral_link.rb
class ReferralLink < ActiveRecord::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
      @promos = Promo.all
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
    before_action :authenticate_admin!, only: [:new, :create, :update, :edit, :destroy, :index, :show_admin]

    def new
        @hotel = Hotel.new
        @islands = Island.all
        @destinations = Destination.all
        render :layout => 'application_nobanner'
    end

    def create
        @hotel = Hotel.new(hotel_params)

        if @hotel.save
            redirect_to hotel_admin_path @hotel, notice: 'Hotel was created successfully'
        end
    end

    def update
        @hotel = Hotel.find(params[:id])

        if @hotel.update!(hotel_params)
            redirect_to hotel_admin_path @hotel, notice: 'Hotel was updated successfully'
        end
    end

    def edit
        @hotel = Hotel.find(params[:id])
        @islands = Island.all
        @destinations = Destination.all
        render :layout => 'application_nobanner'
    end

    def destroy
        hotel = Hotel.find(params[:id])

        if hotel.destroy
            redirect_to hotel_admin_path, notice: 'Hotel was deleted successfully'
        end
    end

    def index
        @hotels = Hotel.all
    end

    def all
        @hotels = Hotel.all
        render :layout => 'application_nobanner'
    end

    def show
        @hotel = Hotel.find(params[:id])
    end

    def show_admin
        @hotel = Hotel.find(params[:id])
        render :layout => 'application_nobanner'
    end

    private
    def hotel_params
        params.require(:hotel).permit(:name, :description, :destination_id, :island_id, :path)
    end
end

app/controllers/promos_controller.rb
class PromosController < ApplicationController
    before_action :authenticate_admin!, only: [:new, :create, :update, :edit, :destroy, :all, :show_admin]
    layout 'application_nobanner'

    def new
        @promo = Promo.new
        @islands = Island.all
    end

    def create
        @promo = Promo.new(promo_params)

        if @promo.save
            redirect_to promo_admin_path @promo, notice: 'Promo was created successfully'
        end
    end

    def update
        promo = Promo.find(params[:id])

        if promo.update!(promo_params)
            redirect_to promo_admin_path promo, notice: 'Promo was updated successfully'
        end
    end

    def edit
        @promo = Promo.find(params[:id])
        @islands = Island.all
    end

    def destroy
        promo = Promo.find(params[:id])

        if promo.destroy
            redirect_to promos_all_path, notice: 'Promo was deleted successfully'
        end
    end

    def index
        @promos = Promo.all
        render :layout => 'application_nobanner'
    end

    def all
        @promos = Promo.all
    end

    def show
        @promo = Promo.find(params[:id])
    end

    def show_admin
        @promo = Promo.find(params[:id])
    end

    private
    def promo_params
        params.require(:promo).permit(:description, :path, :start_date, :end_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hotel_pictures_helper.rb
module HotelPicturesHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/islands_helper.rb
module IslandsHelper
end

app/helpers/promos_helper.rb
module PromosHelper
end

app/views/layouts/_admin_navbar.html.erb
<nav class="navbar navbar-admin navbar-default row" role="navigation">

  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <span class="navbar-brand" href="<%= root_path%>">Manage:</span>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
    <ul class="nav navbar-nav">
      <li><%= link_to("Destinations", destinations_all_path) %></li>
      <li><%= link_to("Islands", islands_all_path) %></li>
      <li><%= link_to("Hotels", hotels_all_path) %></li>
      <li><%= link_to("Promos", promos_all_path)%></li>
    </ul>

    <ul class="nav navbar-nav pull-right">
      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Hello, <%= current_admin.email %><span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to "Edit Profile", edit_admin_registration_path %></li>
          <li><%= link_to "Sign out", destroy_admin_session_path, :method => :delete %></li>
        </ul>
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/_footer.html.erb
<footer>
		<div class="col-sm-6">
		  <p>The Travel Source &copy; <%= Time.now.year %> | 816.525.9859 | <%= mail_to "trvlsrc@sbcglobal.net" %></p>
		</div>
		<div class="col-sm-6 text-right">
		  <p>
		  	<%= link_to "Destinations", destinations_path %> | 
		  	<%= link_to "Promotions", promos_path %> | 
		  	<%= link_to "Contact Us", contact_path %> |
		  	<%= link_to(image_tag("fb.png"), "https://www.facebook.com/trvlsrc", :target => "_blank") %>
		  </p>
		</div>
</footer>

app/views/layouts/_messages.html.erb
<%= bootstrap_flash %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">

  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="<%= root_path%>">Honeymoon Hideaways</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">

      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Destinations<span class="caret"></span></a>
        <ul class="dropdown-menu">
          <% destinations_list.each do |destination| %>
            <li><%= link_to(destination.name, destination_path(destination))%></li>
          <% end %>
          <li><%= link_to("See all", destinations_path)%></li>
        </ul>
      </li>

      
      <li><%= link_to("Promos", promos_path)%></li>
      <li><%= link_to("Contact", contact_index_path)%></li>
    </ul>

    <% if  !admin_signed_in? %>
    <ul class="nav navbar-nav pull-right">
      <li><%= link_to "Login", new_admin_session_path %></li>
    </ul>
    <% end %>

  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- photo credits:
  -->
  <title><%= content_for?(:title) ? yield(:title) : "HoneymoonRails" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  <%= javascript_include_tag "application" %>
</head>
<body>

  <%= render 'layouts/navbar' %>

    <%=
        if  admin_signed_in?
            render 'layouts/admin_navbar'
        end
    %>


  <%= render 'layouts/messages' %>
  <%= yield %>
  <%= render 'layouts/footer' %>


</body>
</html>

app/views/layouts/application_nobanner.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- photo credits:
  -->
  <title><%= content_for?(:title) ? yield(:title) : "HoneymoonRails" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  <%= javascript_include_tag "application" %>
</head>
<body>
  <%= render 'layouts/navbar' %>

  <%=
    if  admin_signed_in?
      render 'layouts/admin_navbar'
    end
  %>
<div class="container">
  <%= render 'layouts/messages' %>

  <%= yield %>
</div>
  <%= render 'layouts/footer' %>


</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- photo credits:
  -->
  <title><%= content_for?(:title) ? yield(:title) : "HoneymoonRails" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  <%= javascript_include_tag "application" %>
</head>
<body>
  <%= render 'layouts/navbar' %>

  <%=
    if  admin_signed_in?
      render 'layouts/admin_navbar'
    end
  %>
<div class="container">
  <%= render 'layouts/messages' %>

  <%= yield %>
</div>
  <%= render 'layouts/footer' %>


</body>
</html>